version: '3'

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpasswd123
  
  cli-app:
    build: app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://taskuser:taskpasswd123@database:5432/mydatabase